# Generated by Django 3.0.4 on 2020-04-05 08:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='a code', max_length=10)),
                ('description', models.CharField(default='some disease', max_length=1000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tz', models.IntegerField(default=123456789)),
                ('birth_date', models.DateField(default=datetime.date.today)),
                ('height', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='A+', max_length=1000)),
                ('vaccines', models.CharField(default='no vaccine', max_length=1000)),
                ('medical_history', models.ManyToManyField(to='account.Disease')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=300)),
                ('university', models.CharField(max_length=300)),
                ('graduation_year', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=300)),
                ('sunday_hours_from', models.TimeField(default='00:00')),
                ('sunday_hours_to', models.TimeField(default='00:00')),
                ('monday_hours_from', models.TimeField(default='00:00')),
                ('monday_hours_to', models.TimeField(default='00:00')),
                ('tuesday_hours_from', models.TimeField(default='00:00')),
                ('tuesday_hours_to', models.TimeField(default='00:00')),
                ('wednesday_hours_from', models.TimeField(default='00:00')),
                ('wednesday_hours_to', models.TimeField(default='00:00')),
                ('thursday_hours_from', models.TimeField(default='00:00')),
                ('thursday_hours_to', models.TimeField(default='00:00')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
