# Generated by Django 3.0.4 on 2020-04-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='vaccines',
            field=models.CharField(choices=[('Hepatitis A', 'Hepatitis A'), ('Hepatitis B', 'Hepatitis B'), ('Diphtheria - Tetanus - Whooping Cough (pertussis)', 'Diphtheria - Tetanus - Whooping Cough (pertussis)'), ('Polio', 'Polio'), ('Pneumococcal', 'Pneumococcal'), ('Rotavirus', 'Rotavirus'), ('Chickenpox (Varicella)', 'Chickenpox (Varicella)'), ('Measles - Mumps - Rubella', 'Measles - Mumps - Rubella'), ('Human PapillomaVirus vaccine', 'Human PapillomaVirus vaccine'), ('Meningococcal conjugate vaccine', 'Meningococcal conjugate vaccine')], default='no vaccine', max_length=1000),
        ),
    ]
