# Generated by Django 3.0.4 on 2020-04-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200405_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='vaccines',
            field=models.CharField(default='Hepatitis A', max_length=1000),
        ),
    ]
