# Generated by Django 3.0.4 on 2020-04-05 08:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default='972551234574', max_length=15)),
                ('booking_date1_date', models.DateField(default=datetime.date.today)),
                ('booking_date1_time', models.TimeField(default='00:00')),
                ('booking_date2_date', models.DateField(default=datetime.date.today)),
                ('booking_date2_time', models.TimeField(default='00:00')),
                ('note', models.TextField(max_length=500)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_meetings', to='account.DoctorProfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_appointments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
